server:
  port: 8080

eureka:
  instance:
    instance-id: API-Gateway
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.16.210.131:8761/eureka/

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: members
          uri: http://172.16.210.131:8081
          predicates:
            - Path=/members/**
          filters:
            - RemoveRequestHeader=Cookie
#            - RewritePath=/members/(?<segment>.*), /$\{segment}

        - id: bookmarks
          uri: http://172.16.210.131:8081
          predicates:
            - Path=/bookmark/**

        - id: board
          uri: http://172.16.210.131:8082
          predicates:
            - Path=/board/**

        - id: comments
          uri: http://172.16.210.131:8083
          predicates:
            - Path=/comments/**

logging:
  level:
    org.springframework.security: DEBUG

